version: '3'
services:
  db:
    image: mysql/mysql-server:5.7
    ports:
      -"3306"
    environment: 
      - MYSQL_ROOT_PASSWORD:rootpwd
      - MYSQL_USER:selene
      - MYSQL_PASSWORD:selene
      - MYSQL_DATABASE:snippet_book
  apachephp:
    build:
    ports:
    links: